module.exports = {
  apps: [
    {
      name: "karupatti-api",
      script: "server.js",
      cwd: "/var/www/karupatti-coffee/Backend",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 5001 },
      env_production: { NODE_ENV: "production", PORT: 5001 },
      max_memory_restart: "300M",
      error_file: "/var/log/karupatti/api-error.log",
      out_file: "/var/log/karupatti/api-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_size: "10M",
      retain: 5,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: "karupatti-frontend",
      script: "npm",
      args: "start -- -p 3001",
      cwd: "/var/www/karupatti-coffee/Frontend",
      instances: 1,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3001 },
      env_production: { NODE_ENV: "production", PORT: 3001 },
      max_memory_restart: "500M",
      error_file: "/var/log/karupatti/frontend-error.log",
      out_file: "/var/log/karupatti/frontend-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      max_size: "10M",
      retain: 5,
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
